/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package confianceoffline;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Font;
import com.itextpdf.text.Font.FontFamily;
import com.itextpdf.text.Image;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.BaseFont;
import com.itextpdf.text.pdf.ColumnText;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfReader;
import com.itextpdf.text.pdf.PdfStamper;
import confianceoffline.gestion_upload.SignOnline;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author User
 */
public class Interface2 extends javax.swing.JFrame {

    /**
     * Creates new form Interface2
     */
    public static String application = "";
    public static String onlineURL = "http://confianceonline.com/";
    public static String signURL = "http://confianceonline.com/centre_certification/signer_desktop.php";
    public static String fileTosign;
    public static String manual_sign_path;
    public static String qr_code_image_path;
    public static String priv_key_path;
    public static String prefixe;
    public static String session_email;
    public static String appDir = "C:\\Confiance";
    public static File signed_file;

    public Interface2() {
        initComponents();
//        setUndecorated(true);
        setSize(new Dimension(1050, 670));
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        loader_pane = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        accueil_pnl = new javax.swing.JPanel();
        acc_pnl_pw = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        acc_pnl_not = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        acc_pnl_cert = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        acc_pnl_sign = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pnl_ges_cert = new javax.swing.JPanel();
        pnl_cert_login = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        pnl_cer_login_mid = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        email_txf_cert = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btn_connexion_cert = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        pwd_txf_cert = new javax.swing.JPasswordField();
        jLabel16 = new javax.swing.JLabel();
        pnl_cert_accueil = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        code_a_rechercher_txf = new javax.swing.JTextField();
        btn_search_cert = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txt_fichier_cert = new javax.swing.JTextField();
        btn_parcours_cert_fic = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txt_cle_cert = new javax.swing.JTextField();
        btn_parcours_cle_certif = new javax.swing.JButton();
        deposer_btn_cert = new javax.swing.JButton();
        info_lbl = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_liste_doc_certif = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\loader2.gif")); // NOI18N

        javax.swing.GroupLayout loader_paneLayout = new javax.swing.GroupLayout(loader_pane);
        loader_pane.setLayout(loader_paneLayout);
        loader_paneLayout.setHorizontalGroup(
            loader_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27)
        );
        loader_paneLayout.setVerticalGroup(
            loader_paneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 51, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Confiance Offline");
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel6.setLayout(new java.awt.CardLayout());

        accueil_pnl.setBackground(new java.awt.Color(29, 78, 101));
        accueil_pnl.setLayout(null);

        acc_pnl_pw.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acc_pnl_pw.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\acc_protection_web.png")); // NOI18N
        jLabel1.setText("jLabel1");
        acc_pnl_pw.add(jLabel1);
        jLabel1.setBounds(0, 0, 250, 140);

        accueil_pnl.add(acc_pnl_pw);
        acc_pnl_pw.setBounds(32, 29, 252, 141);

        acc_pnl_not.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        acc_pnl_not.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\acc_notaire.png")); // NOI18N
        jLabel4.setText("jLabel4");
        acc_pnl_not.add(jLabel4);
        jLabel4.setBounds(0, 0, 240, 140);

        accueil_pnl.add(acc_pnl_not);
        acc_pnl_not.setBounds(574, 29, 239, 141);

        jLabel5.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 102, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Protection web");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accueil_pnl.add(jLabel5);
        jLabel5.setBounds(80, 180, 141, 18);

        jLabel2.setFont(new java.awt.Font("Cambria", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 102, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Le Notaire en ligne");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accueil_pnl.add(jLabel2);
        jLabel2.setBounds(621, 182, 149, 18);

        acc_pnl_cert.setBackground(new java.awt.Color(29, 78, 101));
        acc_pnl_cert.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\acc_certif.png")); // NOI18N
        jLabel3.setText("jLabel3");
        acc_pnl_cert.add(jLabel3);
        jLabel3.setBounds(0, 0, 250, 150);

        accueil_pnl.add(acc_pnl_cert);
        acc_pnl_cert.setBounds(20, 350, 252, 150);

        jLabel6.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 102, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Certification Numérique");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        accueil_pnl.add(jLabel6);
        jLabel6.setBounds(50, 510, 170, 19);

        acc_pnl_sign.setBackground(new java.awt.Color(29, 78, 101));
        acc_pnl_sign.setLayout(null);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\acc_signature.png")); // NOI18N
        jLabel7.setText("jLabel7");
        acc_pnl_sign.add(jLabel7);
        jLabel7.setBounds(0, 0, 240, 140);

        accueil_pnl.add(acc_pnl_sign);
        acc_pnl_sign.setBounds(590, 350, 239, 150);

        jLabel8.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 102, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Signature Numérique");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        accueil_pnl.add(jLabel8);
        jLabel8.setBounds(630, 500, 170, 19);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\acc_homme.png")); // NOI18N
        jLabel9.setText("jLabel9");
        accueil_pnl.add(jLabel9);
        jLabel9.setBounds(250, 0, 330, 630);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("  Copyright © 2019, ITS GROUP. All Rights Reserved. ");
        accueil_pnl.add(jLabel10);
        jLabel10.setBounds(590, 590, 300, 16);

        jPanel6.add(accueil_pnl, "card2");

        pnl_ges_cert.setLayout(new java.awt.CardLayout());

        pnl_cert_login.setLayout(null);
        pnl_cert_login.add(jSeparator1);
        jSeparator1.setBounds(0, 285, 897, 10);

        pnl_cer_login_mid.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\acc_header_2.png")); // NOI18N
        jLabel12.setText("Panneau de connexion");

        jLabel13.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        jLabel13.setText("email                 :");
        jLabel13.setToolTipText("adresse utilisée lors de la création du compte");

        email_txf_cert.setBackground(new java.awt.Color(204, 204, 204));
        email_txf_cert.setForeground(new java.awt.Color(0, 0, 0));
        email_txf_cert.setText("alonla@expressunion.net");

        jLabel14.setFont(new java.awt.Font("Cambria Math", 3, 14)); // NOI18N
        jLabel14.setText("mot de passe    :");
        jLabel14.setToolTipText("adresse utilisée lors de la création du compte");

        btn_connexion_cert.setText("Connexion");
        btn_connexion_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_connexion_certActionPerformed(evt);
            }
        });

        jLabel15.setForeground(new java.awt.Color(51, 102, 255));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Créer un compte");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel26.setForeground(new java.awt.Color(51, 102, 255));
        jLabel26.setText("mot de passe oublié ?");

        pwd_txf_cert.setBackground(new java.awt.Color(204, 204, 204));
        pwd_txf_cert.setForeground(new java.awt.Color(0, 0, 0));
        pwd_txf_cert.setText("abcd1234");

        javax.swing.GroupLayout pnl_cer_login_midLayout = new javax.swing.GroupLayout(pnl_cer_login_mid);
        pnl_cer_login_mid.setLayout(pnl_cer_login_midLayout);
        pnl_cer_login_midLayout.setHorizontalGroup(
            pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_cer_login_midLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(pnl_cer_login_midLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_cer_login_midLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_connexion_cert)
                        .addGap(89, 89, 89))
                    .addGroup(pnl_cer_login_midLayout.createSequentialGroup()
                        .addGroup(pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl_cer_login_midLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(email_txf_cert, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_cer_login_midLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(pwd_txf_cert))
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(32, Short.MAX_VALUE))))
        );
        pnl_cer_login_midLayout.setVerticalGroup(
            pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_cer_login_midLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addGroup(pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(email_txf_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pwd_txf_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_connexion_cert)
                .addGap(18, 18, 18)
                .addGroup(pnl_cer_login_midLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel26))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pnl_cert_login.add(pnl_cer_login_mid);
        pnl_cer_login_mid.setBounds(270, 90, 390, 440);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\Acceuil_back_2.png")); // NOI18N
        jLabel16.setText("jLabel16");
        pnl_cert_login.add(jLabel16);
        jLabel16.setBounds(0, 0, 900, 610);

        pnl_ges_cert.add(pnl_cert_login, "card2");

        pnl_cert_accueil.setLayout(null);

        jPanel1.setLayout(null);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\menu_certif_center.jpg")); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(0, 0, 900, 170);

        pnl_cert_accueil.add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 170);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrez le code de votre fichier ici !", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel19.setText("Code du fichier   :");

        code_a_rechercher_txf.setBackground(new java.awt.Color(204, 204, 204));
        code_a_rechercher_txf.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        code_a_rechercher_txf.setForeground(new java.awt.Color(0, 0, 0));
        code_a_rechercher_txf.setText("XPRE1234567890");
        code_a_rechercher_txf.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        code_a_rechercher_txf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_a_rechercher_txfActionPerformed(evt);
            }
        });

        btn_search_cert.setText("Chercher");
        btn_search_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_search_certActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(code_a_rechercher_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(btn_search_cert, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(code_a_rechercher_txf, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btn_search_cert, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel8);
        jPanel8.setBounds(200, 90, 530, 250);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\back_certif.jpg")); // NOI18N
        jPanel2.add(jLabel18);
        jLabel18.setBounds(0, 0, 900, 410);

        jTabbedPane1.addTab("Retrouver un document", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(null);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chargez votre Document et Votre Clé Privée svp !", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel20.setText("Fichier à déposer     : ");

        txt_fichier_cert.setEditable(false);

        btn_parcours_cert_fic.setText("...");
        btn_parcours_cert_fic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parcours_cert_ficActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 170, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("(NB: format .pdf ou image .jpg, .jpeg, .png)");

        jLabel22.setText("Votre clé privée       : ");

        txt_cle_cert.setEditable(false);

        btn_parcours_cle_certif.setText("...");
        btn_parcours_cle_certif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_parcours_cle_certifActionPerformed(evt);
            }
        });

        deposer_btn_cert.setText("Déposer");
        deposer_btn_cert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deposer_btn_certActionPerformed(evt);
            }
        });

        info_lbl.setForeground(new java.awt.Color(51, 153, 0));
        info_lbl.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        info_lbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                info_lblMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(189, Short.MAX_VALUE)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(info_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(deposer_btn_cert, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_fichier_cert))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txt_cle_cert)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_parcours_cert_fic)
                    .addComponent(btn_parcours_cle_certif))
                .addGap(22, 22, 22))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_fichier_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_parcours_cert_fic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(22, 22, 22)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_cle_cert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_parcours_cle_certif)
                    .addComponent(jLabel22))
                .addGap(28, 28, 28)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deposer_btn_cert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(info_lbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel7);
        jPanel7.setBounds(210, 70, 530, 270);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\back_certif.jpg")); // NOI18N
        jLabel23.setText("jLabel23");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(0, 0, 900, 410);

        jTabbedPane1.addTab("Déposer un document", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel4FocusGained(evt);
            }
        });
        jPanel4.setLayout(null);

        jLabel24.setFont(new java.awt.Font("Cambria", 3, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Liste des documents déposés");
        jPanel4.add(jLabel24);
        jLabel24.setBounds(214, 36, 423, 32);

        table_liste_doc_certif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Date signature", "Nom fichier", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_liste_doc_certif);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(18, 80, 866, 320);

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\back_certif.jpg")); // NOI18N
        jPanel4.add(jLabel25);
        jLabel25.setBounds(0, 0, 900, 420);

        jTabbedPane1.addTab("Mes documents", jPanel4);
        jTabbedPane1.addTab("Aide", jPanel5);

        pnl_cert_accueil.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 170, 900, 440);

        pnl_ges_cert.add(pnl_cert_accueil, "card3");

        jPanel6.add(pnl_ges_cert, "card3");

        getContentPane().add(jPanel6);
        jPanel6.setBounds(90, 0, 900, 610);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\User\\Pictures\\confianceOffline\\Acceuil_back.png")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1040, 620);

        jMenu1.setText("Fichier");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Quitter");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Modules");

        jMenuItem2.setText("Protection web");
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Le Notaire en ligne");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Certification Numérique");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Signature Numérique");
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void code_a_rechercher_txfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_a_rechercher_txfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_a_rechercher_txfActionPerformed

    private void btn_parcours_cert_ficActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parcours_cert_ficActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF Files", "pdf");
        jfc.setFileFilter(filter);
        jfc.addChoosableFileFilter(new FileNameExtensionFilter("Image", "jpg"));
        jfc.addChoosableFileFilter(new FileNameExtensionFilter("Image", "png"));
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            fileTosign = file.getAbsolutePath();
            txt_fichier_cert.setText(fileTosign);

        }

    }//GEN-LAST:event_btn_parcours_cert_ficActionPerformed

    private void btn_connexion_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_connexion_certActionPerformed
        // TODO add your handling code here:
        if (!email_txf_cert.getText().equals("") && email_txf_cert.getText().contains("@") && !pwd_txf_cert.getText().equals("")) {
            try {
                if (Connection.checkInternet()) {
                    Connection con = new Connection(email_txf_cert.getText(), pwd_txf_cert.getText(), application, onlineURL + application + "/connexion.php");
                    if (con.Connect()) {
                        session_email = email_txf_cert.getText();
                        (new File(appDir + "\\" + application + "\\Documents")).mkdirs();
                        pnl_cert_login.setVisible(false);
                        pnl_cert_accueil.setVisible(true);
                        String[] titre = new String[4];
                        titre[0] = "No";
                        titre[1] = "Date de signature";
                        titre[2] = "Nom du document";
                        titre[3] = "Type";
                        String[][] liste_doc = Commons.mesDocuments(appDir + "\\" + application + "\\Documents");
                        table_liste_doc_certif.setModel(new javax.swing.table.DefaultTableModel(liste_doc, titre));

                    } else {
                        JOptionPane.showMessageDialog(null, "Bien vouloir verifier les parametres de connexion !!!");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Bien vouloir vérifier votre connexion Internet !!!");
                }
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_btn_connexion_certActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        accueil_pnl.setVisible(false);
        pnl_ges_cert.setVisible(true);
        application = "centre_certification";
    }//GEN-LAST:event_jLabel6MouseClicked

    private void deposer_btn_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deposer_btn_certActionPerformed
        // TODO add your handling code here:

        try {
            if ("".equals(txt_fichier_cert.getText()) || "".equals(txt_cle_cert.getText())) {
                JOptionPane.showMessageDialog(null, "Bien vouloir charger tous les fichiers nécessaires");
            } else {
                deposer_btn_cert.setEnabled(false);

                info_lbl.setText("trying to upload files on server...");
                String charset = "UTF-8";
                File uploadFile1 = new File(fileTosign);
                File uploadFile2 = new File(priv_key_path);
//            File uploadFile3 = new File(manual_sign_path);

                try {
                    String today = Commons.getTodayDate();
                    SignOnline multipart = new SignOnline(signURL, charset);

                    multipart.addHeaderField("User-Agent", "CodeJava");
                    multipart.addHeaderField("Test-Header", "Header-Value");

                    multipart.addFormField("email", session_email);
//                multipart.addFormField("prefixe", prefixe);

                    multipart.addFilePart("fichier_claire", uploadFile1);
                    multipart.addFilePart("clee_priv", uploadFile2);
//                multipart.addFilePart("clee_priv", uploadFile2);

                    String response = multipart.finish();
                    System.out.println("response = " + response);
                    GsonBuilder builder = new GsonBuilder(); 
                    builder.setPrettyPrinting(); 
                    Gson gson = builder.create(); 
                    Result result = gson.fromJson(response, Result.class); 
                    System.out.println(result);  
                    String fichier_qr = result.getQrcode_path();
                    String fichier_sign = result.getSigned_file();
                    
                    System.out.println("fichier_qr = "+fichier_qr+"  fichier_sign = "+fichier_sign);
                    info_lbl.setText("response received from server ...");
//                    String file_to_download = response.substring(response.length() - 44);
                    String file_to_download = fichier_sign;
                    System.out.println("response = " + file_to_download);
                    String fileURL = onlineURL + "/" + application + "/signatures/" + file_to_download;
                    String saveDir = appDir + "\\" + application + "\\Documents\\" + today;
                    (new File(saveDir)).mkdirs();
                    info_lbl.setText("saving file ...");
                    if (multipart.downloadFile(fileURL, saveDir)) {
                        signed_file = new File(saveDir + File.separator + "signed_" + uploadFile1.getName());
                        (new File(saveDir + File.separator + file_to_download)).renameTo(signed_file);
                        info_lbl.setText("fichier déposé ! cliquez pour ouvrir");
                        String[] titre = new String[4];
                        titre[0] = "No";
                        titre[1] = "Date de signature";
                        titre[2] = "Nom du document";
                        titre[3] = "Type";
                        String[][] liste_doc = Commons.mesDocuments(appDir + "\\" + application + "\\Documents");
                        table_liste_doc_certif.setModel(new javax.swing.table.DefaultTableModel(liste_doc, titre));
                    } else {
//                        String[] tab = response.split("||");

//                        String qr_code_path = tab[0].substring(tab[0].length() - 39);
                        String qr_code_path = fichier_qr;
                        System.out.println("QR CODE file is in " + qr_code_path);
                        String saveDir2 = appDir + "\\" + application + "\\Documents\\temp\\" + today;
                        (new File(saveDir2)).mkdirs();
                        if (multipart.downloadFile(onlineURL + "/" + application + "/traitements/" + qr_code_path, saveDir2)) {
                            String temp_qr = saveDir2 + File.separator + qr_code_path;

                            //si PDF
                            String extension = uploadFile1.getName().substring(uploadFile1.getName().length() - 3);
                            if (".pdf".equals(extension)) {
                                String output_sign_file = saveDir + File.separator + "sign_" + uploadFile1.getName();
                                PdfReader reader = new PdfReader(fileTosign);
                                PdfStamper stamper = new PdfStamper(reader, new FileOutputStream(output_sign_file));
                                int pages = reader.getNumberOfPages();
//            //Iterate the pdf through pages.
                                for (int i = 1; i <= pages; i++) {
                                    PdfContentByte content = stamper.getOverContent(i);
                                    Image image = Image.getInstance(temp_qr);
                                    image.scaleAbsoluteHeight(50);
                                    image.scaleAbsoluteWidth((image.getWidth() * 50) / image.getHeight());
                                    image.setAbsolutePosition(500, 50);
                                    content.addImage(image);
                                    Font bold = new Font(FontFamily.COURIER, 12, Font.BOLD);
                                    Chunk chunk = new Chunk("Click to verify", bold);
                                    chunk.setAnchor("http://confianceonline.com/" + application);
                                    Phrase p = new Phrase("");
                                    p.add(chunk);
                                    ColumnText ct = new ColumnText(content);
                                    ct.setSimpleColumn(450, 350, 559, 400);
                                    ct.addText(p);
                                    ct.go();
                                }
                                stamper.close();
                                PdfReader pdfReader = new PdfReader(fileTosign);
                                //Create PdfStamper instance.
                                PdfStamper pdfStamper = new PdfStamper(pdfReader, new FileOutputStream(output_sign_file));
                                //Create BaseFont instance.
                                BaseFont baseFont = BaseFont.createFont(
                                        BaseFont.TIMES_ROMAN,
                                        BaseFont.CP1252, BaseFont.NOT_EMBEDDED);
                            //Get the number of pages in pdf.

                                //Close the pdfStamper.
                                pdfStamper.close();
                                info_lbl.setText("fichier déposé ! cliquez pour ouvrir");
                                String[] titre = new String[4];
                                titre[0] = "No";
                                titre[1] = "Date de signature";
                                titre[2] = "Nom du document";
                                titre[3] = "Type";
                                String[][] liste_doc = Commons.mesDocuments(appDir + "\\" + application + "\\Documents");
                                table_liste_doc_certif.setModel(new javax.swing.table.DefaultTableModel(liste_doc, titre));
                            }
                            else{
                                info_lbl.setForeground(Color.red);
                                info_lbl.setText("impossible de signer le fichier");
                            }
                        }
                    }

                } catch (IOException ex) {
                    System.err.println(ex);
                }
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
        deposer_btn_cert.setEnabled(true);

    }//GEN-LAST:event_deposer_btn_certActionPerformed

    private void btn_parcours_cle_certifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_parcours_cle_certifActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Key files", "key", "perm");
        jfc.setFileFilter(filter);
        int returnVal = jfc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = jfc.getSelectedFile();
            priv_key_path = file.getAbsolutePath();
            txt_cle_cert.setText(priv_key_path);

        }
    }//GEN-LAST:event_btn_parcours_cle_certifActionPerformed

    private void info_lblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_info_lblMouseClicked
        try {
            // TODO add your handling code here:
            Desktop.getDesktop().open(signed_file);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }//GEN-LAST:event_info_lblMouseClicked

    private void jPanel4FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel4FocusGained
        // TODO add your handling code here:


    }//GEN-LAST:event_jPanel4FocusGained

    private void btn_search_certActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_search_certActionPerformed
        // TODO add your handling code here:
        String code_a_rechercher = code_a_rechercher_txf.getText();
        if(code_a_rechercher.equals("")){
            JOptionPane.showMessageDialog(null, "le code ne peut être vide");
        }
        else{
            
        }
    }//GEN-LAST:event_btn_search_certActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interface2().setVisible(true);
            }
        });
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel acc_pnl_cert;
    private javax.swing.JPanel acc_pnl_not;
    private javax.swing.JPanel acc_pnl_pw;
    private javax.swing.JPanel acc_pnl_sign;
    private javax.swing.JPanel accueil_pnl;
    private javax.swing.JButton btn_connexion_cert;
    private javax.swing.JButton btn_parcours_cert_fic;
    private javax.swing.JButton btn_parcours_cle_certif;
    private javax.swing.JButton btn_search_cert;
    private javax.swing.JTextField code_a_rechercher_txf;
    private javax.swing.JButton deposer_btn_cert;
    private javax.swing.JTextField email_txf_cert;
    private javax.swing.JLabel info_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel loader_pane;
    private javax.swing.JPanel pnl_cer_login_mid;
    private javax.swing.JPanel pnl_cert_accueil;
    private javax.swing.JPanel pnl_cert_login;
    private javax.swing.JPanel pnl_ges_cert;
    private javax.swing.JPasswordField pwd_txf_cert;
    private javax.swing.JTable table_liste_doc_certif;
    private javax.swing.JTextField txt_cle_cert;
    private javax.swing.JTextField txt_fichier_cert;
    // End of variables declaration//GEN-END:variables
}
